version: "{build}"

# shallow_clone: true

# environment:
#   MAKEFLAGS: -j4

build:
  verbosity: normal

environment:
  matrix:
  - COMPILER: msys2
    PLATFORM: x64
    MSYS2_ARCH: x86_64
    MSYS2_DIR: msys64
    MSYSTEM: MINGW64
    BIT: 64

install:
  - cmd: |
      SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
      choco install haskell-stack
      bash .appveyor/helper.sh prepare

cache:
  - ghc -> ghc/git-rev-sha1

build_script:
  - bash .appveyor/helper.sh build-ghc
  - bash .appveyor/helper.sh build-asterius

deploy: off
test: off
