version: 0.0.1.{build}

shallow_clone: true

environment:
  MAKEFLAGS: -j4

build_script:
  - choco install haskell-stack
  - stack --no-terminal --skip-msys setup > NUL
  - mklink /D %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025 C:\\msys64
  - copy %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\ghc-8.5.*.installed %LOCALAPPDATA%\\Programs\\stack\\x86_64-windows\\msys2-20161025.installed
  - stack --no-terminal exec pacman -- -S autoconf coreutils make mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc --needed --noconfirm --noprogressbar
  - stack --no-terminal test wasm-toolkit:nir-test
  - stack --no-terminal test asterius:fact-dump
  - stack --no-terminal test asterius:ahc-boot
  - stack --no-terminal test asterius:rts-cmm

test: off
