site_name: Asterius
site_url: https://tweag.github.io/asterius
repo_url: https://github.com/tweag/asterius
pages:
  - 'Introduction': 'index.md'
  - 'Building guide': 'building.md'
  - 'Project roadmap': 'roadmap.md'
theme: readthedocs
