site_name: Asterius
site_url: https://tweag.github.io/asterius
repo_url: https://github.com/tweag/asterius
pages:
  - 'Home': 'index.md'
  - 'Building guide': 'building.md'
  - 'Using ahc-link': 'ahc-link.md'
  - 'JavaScript FFI': 'jsffi.md'
  - 'Invoking RTS API in JavaScript': 'rts-api.md'
  - 'The runtime debugging feature': 'debugging.md'
  - 'Project architecture': 'architecture.md'
  - 'Writing WebAssembly code in Haskell': 'wasm-in-hs.md'
  - 'WebAssembly as a Haskell compilation target': 'webassembly.md'
  - 'Reading list': 'readings.md'
  - 'Checklist': 'checklist.md'
theme: readthedocs
