site_name: Asterius
site_url: https://tweag.github.io/asterius
repo_url: https://github.com/tweag/asterius
pages:
  - 'Home': 'index.md'
  - For users:
    - 'Building guide': 'building.md'
  - For developers:
    - 'JavaScript FFI': 'jsffi.md'
    - 'The runtime debugging feature': 'debugging.md'
    - 'Project architecture': 'architecture.md'
    - 'WebAssembly as a Haskell compilation target': 'webassembly.md'
    - 'Reading list': 'readings.md'
theme: readthedocs
