site_name: Asterius
site_url: https://tweag.github.io/asterius
repo_url: https://github.com/tweag/asterius
pages:
  - 'Home': 'index.md'
  - For users:
    - 'Building guide': 'building.md'
  - For developers:
    - 'Project architecture': 'architecture.md'
    - 'About WebAssembly': 'webassembly.md'
    - 'Project roadmap': 'roadmap.md'
theme: readthedocs
