resolver: ghc-8.5
allow-newer: true
flags:
  hashable:
    integer-gmp: false
extra-deps:
  - cereal-0.5.5.0
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - pretty-show-1.7
  - primitive-0.6.3.0
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
packages:
  - asterius
  - genapply
  - ghc-toolkit
  - binaryen
setup-info:
  ghc:
    windows64:
      8.5.20180413:
        url: https://felis.sapiens.moe/ghc-8.5.20180413-x86_64-unknown-mingw32.tar.xz
        sha256: b4e511f04e75bed048dd5eeffa05e642284fa22d8c49d7306029c2951b4d135f
