resolver: ghc-8.5
allow-newer: true
flags:
  hashable:
    integer-gmp: false
extra-deps:
  - abstract-deque-0.3
  - abstract-par-0.3.3
  - async-2.2.1
  - cereal-0.5.5.0
  - clock-0.7.2
  - compact-0.1.0.1
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - math-functions-0.2.1.0
  - monad-par-0.3.4.8
  - monad-par-extras-0.3.3
  - mwc-random-0.13.6.0
  - parallel-3.2.1.1
  - pretty-show-1.7
  - primitive-0.6.3.0
  - random-1.1
  - unliftio-0.2.6.0
  - unliftio-core-0.1.1.0
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
  - vector-th-unbox-0.2.1.6
packages:
  - asterius
  - ghc-toolkit
  - binaryen
  - wasm-toolkit
setup-info:
  ghc:
    windows64:
      8.5.20180326:
        url: https://felis.sapiens.moe/ghc-8.5.20180326-x86_64-unknown-mingw32.tar.xz
        sha256: 043c2b606f5348be3db1475caa997352aa40741cb898cc53686ef703c1ff0ae0
