resolver: ghc-8.7
allow-newer: true
extra-deps:
  - ansi-terminal-0.8.0.4
  - ansi-wl-pprint-0.6.8.2
  - colour-2.3.4
  - mintty-0.1.2
  - optparse-applicative-0.14.2.0
  - transformers-compat-0.6.2
packages:
  - asterius
  - binaryen
  - ghc-toolkit
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.7.20180822:
        url: https://ci.appveyor.com/api/buildjobs/a0ism43pxm9f4371/artifacts/ghc/ghc-8.7.20180822-x86_64-unknown-mingw32.tar.xz
    linux64:
      8.7.20180822:
        url: https://1593-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.7.20180822-x86_64-unknown-linux.tar.xz
