resolver: ghc-8.7
allow-newer: true
extra-deps:
  - ansi-terminal-0.8.1
  - ansi-wl-pprint-0.6.8.2
  - colour-2.3.4
  - mintty-0.1.2
  - optparse-applicative-0.14.2.0
  - transformers-compat-0.6.2
packages:
  - asterius
  - binaryen
  - ghc-toolkit
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.7.20180918:
        url: https://ci.appveyor.com/api/buildjobs/f2bwtfsd3a8echh6/artifacts/ghc/ghc-bindist/ghc-8.7.20180918-x86_64-unknown-mingw32.tar.xz
        sha256: ee156ff47752ab76e8c2b329e90d9adb736799064455bfc20dce98380a27b2df
    linux64:
      8.7.20180918:
        url: https://1647-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.7.20180918-x86_64-unknown-linux.tar.xz
        sha256: 1771e0e9a472c32636fda974fd428cded08e4ed6db6ce1d075c3a801922ac7a3
