resolver: ghc-8.5
allow-newer: true
flags:
  hashable:
    integer-gmp: false
extra-deps:
  - async-2.2.1
  - cereal-0.5.5.0
  - clock-0.7.2
  - extra-1.6.4
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - pretty-show-1.7
  - primitive-0.6.3.0
  - unliftio-0.2.5.0
  - unliftio-core-0.1.1.0
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
packages:
  - asterius
  - cereal-utils
  - ghc-toolkit
  - hbinaryen
  - wasm-toolkit
