resolver: ghc-8.7
allow-newer: true
extra-deps:
  - ansi-terminal-0.8.1
  - ansi-wl-pprint-0.6.8.2
  - colour-2.3.4
  - mintty-0.1.2
  - optparse-applicative-0.14.2.0
  - transformers-compat-0.6.2
packages:
  - asterius
  - binaryen
  - ghc-toolkit
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.7.20180920:
        url: https://ci.appveyor.com/api/buildjobs/hnl00glf483ds970/artifacts/ghc/ghc-bindist/ghc-8.7.20180920-x86_64-unknown-mingw32.tar.xz
        sha256: 497cba035f22d8e9b45ea53063f5f8b82d9041cda49835a3e706e55aa0432d7d
    linux64:
      8.7.20180920:
        url: https://1660-111412813-gh.circle-artifacts.com/0/tmp/ghc-bindist/ghc-8.7.20180920-x86_64-unknown-linux.tar.xz
        sha256: 35d9a6ab1e926ea1a897d7701b2794350e4530239b34c266ba9cc911568e35d2
