resolver: ghc-8.5
allow-newer: true
flags:
  hashable:
    integer-gmp: false
extra-deps:
  - async-2.2.1
  - cereal-0.5.5.0
  - clock-0.7.2
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - pretty-show-1.7
  - primitive-0.6.3.0
  - unliftio-0.2.5.0
  - unliftio-core-0.1.1.0
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
packages:
  - asterius
  - ghc-toolkit
  - binaryen
  - wasm-toolkit
setup-info:
  ghc:
    windows64:
      8.5.20180308:
        url: https://felis.sapiens.moe/ghc-8.5.20180308-x86_64-unknown-mingw32.tar.xz
        sha256: 3a079c820043eb41b5d31be3ed97824ecd918fb77788547a4ed324da9bb9f6b1
