version: 2

jobs:
  asterius:
    docker:
      - image: terrorjack/vanilla:circleci
    environment:
      MAKEFLAGS: -j4
      XZ_OPT: -9
      NIXPKGS_REV: 4cc8c2955fe132c3c780cdce41746ea77fcfe687
    steps:
      - checkout
      - run: |
          export PREV_DIR=`pwd`
          cd /tmp
          nix-env -iA \
            nixpkgs.curlFull \
            nixpkgs.unzip
          curl -L https://github.com/TerrorJack/nixpkgs/archive/$NIXPKGS_REV.zip -o nixpkgs-$NIXPKGS_REV.zip
          unzip -q nixpkgs-$NIXPKGS_REV.zip
          cd nixpkgs-$NIXPKGS_REV
          nix-env -f . -iA haskell.compiler.ghcAsterius --option require-sigs false --option extra-binary-caches https://canis.sapiens.moe/
          cd $PREV_DIR
          unset PREV_DIR

          nix-env -iA \
            nixpkgs.autoconf \
            nixpkgs.binutils_nogold \
            nixpkgs.cmake \
            nixpkgs.coreutils \
            nixpkgs.findutils \
            nixpkgs.gcc \
            nixpkgs.gnumake \
            nixpkgs.lzma \
            nixpkgs.nodejs-9_x \
            nixpkgs.stack
          stack --no-terminal --system-ghc test --haddock asterius:fact-dump
          stack --no-terminal --system-ghc test --haddock asterius:ahc-boot
          if [ $CIRCLE_PROJECT_USERNAME == "tweag" ]
          then
            export PREV_DIR=`pwd`
            cp -r `stack --no-terminal --system-ghc path --local-doc-root` /tmp/
            cd /tmp/doc
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Haddock documentation of tweag/asterius@$CIRCLE_SHA1"
            git push https://TerrorJack:$GH_TOKEN@github.com/tweag/asterius.git gh-pages --force
            cd $PREV_DIR
            unset PREV_DIR
          fi
          cd /tmp
          tar -cJf /tmp/asterius_boot.tar.xz asterius/.boot
      - store_artifacts:
          path: /tmp/asterius_boot.tar.xz

  binaryen:
    docker:
      - image: terrorjack/vanilla:haskell
    environment:
      - MAKEFLAGS: -j4
    steps:
      - checkout
      - restore_cache:
          key: binaryen-stack-work
      - run: stack --no-terminal --resolver ghc-8.4.1 --nix-packages "cmake gcc gnumake" test --haddock --flag hashable:integer-gmp binaryen:binaryen-test
      - save_cache:
          key: binaryen-stack-work-{{ .BuildNum }}
          paths:
            - /root/.stack
            - .stack-work
            - binaryen/.stack-work

workflows:
  version: 2
  build:
    jobs:
      - asterius
      - binaryen
