version: 2

jobs:
  asterius:
    resource_class: xlarge # otherwise compiling GHC may take a while
    docker:
      - image: ghcci/x86_64-linux:0.0.1
    environment:
      JOBS: 9
    steps:
      - checkout
      # CircleCI does not checkout submodules, so we must do it ourselves.
      - run: git submodule sync
      - run: git submodule update --init --recursive
      - run:
          name: Install some packages
          command: |
            sudo apt-get update -qq
            sudo apt-get install -qy python-sphinx cmake nodejs-legacy python3 python3-pip
            sudo pip3 install mkdocs
            which mkdocs
      - run:
          name: Write commit hash to a file
          command: |
            cd ghc
            git rev-parse HEAD > git-rev-sha1
      - restore_cache:
          keys:
            - ghc-build-cache-{{ checksum "ghc/git-rev-sha1" }}-
      - run:
          name: Compile GHC
          command: |
            if ! [ -f ghc/ghc-compiled ]
            then
              cp -v .circleci/build.mk ghc/mk/build.mk
              cd ghc
              ./boot
              ./configure
              make -j$JOBS
              touch ghc-compiled
            fi
      - save_cache:
          key: ghc-build-cache-{{ checksum "ghc/git-rev-sha1" }}-{{ .BuildNum }}
          paths: "ghc"
      - run:
          name: Install GHC
          command: |
            cd ghc
            sudo make install
      - run:
          name: Drop boot GHC
          command: |
            sudo rm -rfv /opt/ghc/
      - run:
          name: Check that we have the right GHC version installed
          command: |
            ghc --version
      - restore_cache:
          keys:
            - stack-home-ghc-8.5
      - restore_cache:
          keys:
            - stack-work-ghc-8.5
      - run:
          name: Test Asterius
          command: |
            stack --no-terminal --system-ghc exec --haddock ahc-boot
            stack --no-terminal --system-ghc test --haddock asterius:ahc-boot-builtins
            stack --no-terminal --system-ghc test --haddock asterius:fact-dump
      - save_cache:
          key: stack-home-ghc-8.5
          paths: "~/.stack"
      - save_cache:
          key: stack-work-ghc-8.5
          paths: ".stack-work"
      - run:
          name: Test generation of documentation
          command: |
            export PREV_DIR=`pwd`
            mkdocs build
            cp -r site /tmp/
            cp -r `stack --no-terminal --system-ghc path --local-doc-root` /tmp/site/haddock
      - persist_to_workspace:
          root: /tmp
          paths:
            - site

  asterius-push-docs:
    docker:
      - image: ghcci/x86_64-linux:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Ensure that GitHub is a known host (SSH)
          command: |
            if [ -z `ssh-keygen -F github.com` ]; then
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            fi
      - run:
          name: Push documentation to gh-pages
          command: |
            cd /tmp/site
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Documentation of tweag/asterius@$CIRCLE_SHA1"
            git push git@github.com:tweag/asterius.git gh-pages --force

workflows:
  version: 2
  build:
    jobs:
      - asterius
      - asterius-push-docs:
          requires:
            - asterius
          filters:
            branches:
              only: master
