version: 2

jobs:
  build:
    docker:
      - image: terrorjack/meikyu:ghc-head
    environment:
      MAKEFLAGS: -j4
      XZ_OPT: -9
    steps:
      - checkout
      - restore_cache:
          key: stack-work-gen5-
      - run: |
          apk add --no-cache --no-progress \
              autoconf \
              cmake \
              coreutils \
              findutils \
              g++ \
              make \
              nodejs-current \
              sed \
              xz
          stack --no-terminal test --haddock hbinaryen:hbinaryen-test
          stack --no-terminal test --haddock asterius:fact-dump
          stack --no-terminal test --haddock asterius:ahc-boot
          if [ $CIRCLE_PROJECT_USERNAME == "tweag" ] && [ $CIRCLE_BRANCH == "master" ]
          then
            export PREV_DIR=`pwd`
            cp -r `stack path --local-doc-root` /tmp/
            cd /tmp/doc
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Haddock documentation of tweag/asterius@$CIRCLE_SHA1"
            git push https://TerrorJack:$GH_TOKEN@github.com/tweag/asterius.git gh-pages --force
            cd $PREV_DIR
            unset PREV_DIR
          fi
          cd /tmp/asterius/.boot
          tar -cJf /tmp/asterius_boot.tar.xz asterius_lib dist
          rm -rf /root/.stack/programs
      - store_artifacts:
          path: /tmp/asterius_boot.tar.xz
      - save_cache:
          key: stack-work-gen5-{{ .BuildNum }}
          paths:
            - /root/.stack
            - .stack-work
            - asterius/.stack-work
            - cereal-utils/.stack-work
            - ghc-toolkit/.stack-work
            - hbinaryen/.stack-work
            - wasm-toolkit/.stack-work
            - asterius/.lbi.buildinfo
