version: 2

jobs:
  build:
    docker:
      - image: terrorjack/meikyu:ghc-head
    steps:
      - checkout
      - restore_cache:
          key: stack-work-
      - run: |
          apk add --no-cache --no-progress \
              autoconf \
              cmake \
              g++ \
              make \
              nodejs-current \
              sed
          MAKEFLAGS=-j4 stack --no-terminal build --test --no-run-tests
          mv /root/.stack/programs /tmp/
      - save_cache:
          key: stack-work-{{ .BuildNum }}
          paths:
            - /root/.stack
            - .stack-work
            - asterius/.stack-work
            - cereal-utils/.stack-work
            - hbinaryen/.stack-work
            - wasm-toolkit/.stack-work
            - asterius/.lbi.buildinfo
      - run: |
          mv /tmp/programs /root/.stack/
          stack --no-terminal test hbinaryen:hbinaryen-test
          stack --no-terminal test asterius:fact-dump
          stack --no-terminal test asterius:ahc-boot
