version: 2

jobs:
  asterius:
    docker:
      - image: terrorjack/vanilla:circleci
    environment:
      MAKEFLAGS: -j4
      XZ_OPT: -9
      NIXPKGS_REV: fadcbfc2f593301c7dc22447ba1d7eed3549b1ac
    steps:
      - checkout
      - run: |
          nix-channel --update
          nix-env -iA \
            nixpkgs.autoconf \
            nixpkgs.binutils_nogold \
            nixpkgs.cmake \
            nixpkgs.coreutils \
            nixpkgs.curlFull \
            nixpkgs.gcc \
            nixpkgs.gnumake \
            nixpkgs.mkdocs \
            nixpkgs.nodejs-9_x \
            nixpkgs.stack \
            nixpkgs.unzip

          export PREV_DIR=`pwd`
          cd /tmp
          curl -L https://github.com/TerrorJack/asterius-nixpkgs/archive/$NIXPKGS_REV.zip -o asterius-nixpkgs-$NIXPKGS_REV.zip
          unzip -q asterius-nixpkgs-$NIXPKGS_REV.zip
          cd asterius-nixpkgs-$NIXPKGS_REV
          nix-env -f . -iA haskell.compiler.ghcAsterius --option require-sigs false --option extra-binary-caches https://canis.sapiens.moe/
          cd $PREV_DIR
          unset PREV_DIR

          stack --no-terminal --system-ghc test --haddock wasm-toolkit:nir-test
          stack --no-terminal --system-ghc test --haddock asterius:fact-dump
          stack --no-terminal --system-ghc exec ahc-boot
          if [ $CIRCLE_PROJECT_USERNAME == "tweag" ] && [ $CIRCLE_BRANCH == "master" ]
          then
            export PREV_DIR=`pwd`
            mkdocs build
            cp -r site /tmp/
            cp -r `stack --no-terminal --system-ghc path --local-doc-root` /tmp/site/haddock
            cd /tmp/site
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Documentation of tweag/asterius@$CIRCLE_SHA1"
            git push https://TerrorJack:$GH_TOKEN@github.com/tweag/asterius.git gh-pages --force
            cd $PREV_DIR
            unset PREV_DIR
          fi

  binaryen:
    docker:
      - image: terrorjack/vanilla:haskell
    environment:
      - MAKEFLAGS: -j4
    steps:
      - checkout
      - run: |
          nix-channel --update
          stack --no-terminal --resolver ghc-8.4.1 --nix-packages "cmake gcc gnumake" test --haddock --flag hashable:integer-gmp binaryen:binaryen-test

workflows:
  version: 2
  build:
    jobs:
      - asterius
      - binaryen
