version: 2

jobs:
  build:
    docker:
      - image: terrorjack/meikyu:ghc-head
    environment:
      MAKEFLAGS: -j4
      XZ_OPT: -9
    steps:
      - checkout
      - restore_cache:
          key: stack-work-
      - run: |
          apk add --no-cache --no-progress \
              autoconf \
              cmake \
              coreutils \
              findutils \
              g++ \
              make \
              nodejs-current \
              sed \
              xz
          stack --no-terminal test hbinaryen:hbinaryen-test
          stack --no-terminal test asterius:fact-dump
          stack --no-terminal test asterius:ahc-boot
          cd /tmp/asterius/.boot
          find . -name '*.ddump-*' | tar -cJf /tmp/asterius_boot.tar.xz -T -
          rm -rf /root/.stack/programs
      - store_artifacts:
          path: /tmp/asterius_boot.tar.xz
      - save_cache:
          key: stack-work-{{ .BuildNum }}
          paths:
            - /root/.stack
            - .stack-work
            - asterius/.stack-work
            - cereal-utils/.stack-work
            - hbinaryen/.stack-work
            - wasm-toolkit/.stack-work
            - asterius/.lbi.buildinfo
