name: ghc-toolkit
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

data-files:
  - boot-libs/**/**

custom-setup:
  dependencies:
    - base
    - Cabal
    - containers
    - directory
    - filepath

flags:
  build-orphans:
    description: Build Language.Haskell.GHC.Toolkit.IROrphans. Breaks compatibility with ghc-8.4.1.
    default: false
    manual: false

ghc-options: -Wall

dependencies:
  - base
  - binary
  - Cabal
  - containers
  - directory
  - filepath
  - ghc
  - process

library:
  source-dirs: src
  when:
    - condition: flag(build-orphans)
      then:
        exposed-modules:
          - Language.Haskell.GHC.Toolkit.BuildInfo
          - Language.Haskell.GHC.Toolkit.Compiler
          - Language.Haskell.GHC.Toolkit.FakeGHC
          - Language.Haskell.GHC.Toolkit.FrontendPlugin
          - Language.Haskell.GHC.Toolkit.GenPaths
          - Language.Haskell.GHC.Toolkit.Hooks
          - Language.Haskell.GHC.Toolkit.IROrphans
          - Language.Haskell.GHC.Toolkit.Run
        other-extensions:
          - FlexibleInstances
          - GADTs
          - NamedFieldPuns
          - RecordWildCards
          - StandaloneDeriving
          - StrictData
          - UnboxedTuples
          - UndecidableInstances
      else:
        exposed-modules:
          - Language.Haskell.GHC.Toolkit.BuildInfo
          - Language.Haskell.GHC.Toolkit.Compiler
          - Language.Haskell.GHC.Toolkit.FakeGHC
          - Language.Haskell.GHC.Toolkit.FrontendPlugin
          - Language.Haskell.GHC.Toolkit.GenPaths
          - Language.Haskell.GHC.Toolkit.Hooks
          - Language.Haskell.GHC.Toolkit.Run
        other-extensions:
          - NamedFieldPuns
          - RecordWildCards
          - StrictData
          - UnboxedTuples
