name: cereal-utils
version: 0.0.1
category: Data
stability: alpha
maintainer: Shao Cheng <astrohavoc@gmail.com>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - base
  - bytestring
  - cereal
  - hashable
  - unordered-containers
  - vector

library:
  source-dirs: src
