name: asterius
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md
  - test/fact-dump/Fact.hs

data-files:
  - boot.sh

custom-setup:
  dependencies:
    - base
    - Cabal
    - ghc-toolkit

ghc-options: -Wall

dependencies:
  - acid-state
  - base
  - binary
  - binaryen
  - bytestring
  - Cabal
  - cereal
  - containers
  - deepseq
  - directory
  - filepath
  - ghc
  - ghc-toolkit
  - hashable
  - monad-par
  - monad-par-extras
  - mtl
  - pretty-show
  - template-haskell
  - unliftio
  - unordered-containers
  - vector
  - wasm-toolkit

library:
  source-dirs: src
  other-modules: Paths_asterius
  other-extensions:
    - DeriveGeneric
    - DeriveDataTypeable
    - FlexibleContexts
    - GADTs
    - GeneralizedNewtypeDeriving
    - LambdaCase
    - MagicHash
    - NamedFieldPuns
    - OverloadedLists
    - OverloadedStrings
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - TypeFamilies
    - UnboxedTuples

executables:
  ahc:
    source-dirs: app
    main: ahc.hs
    dependencies:
      - asterius

tests:
  ahc-boot:
    source-dirs: test
    main: ahc-boot.hs
    dependencies:
      - asterius

  fact-dump:
    source-dirs: test
    main: fact-dump.hs
    dependencies:
      - asterius

  rts-cmm:
    source-dirs: test
    main: rts-cmm.hs
    dependencies:
      - asterius
