name: wasm-toolkit
version: 0.0.1
category: Compiler
stability: alpha
maintainer: Shao Cheng <cheng.shao@tweag.io>
copyright: (c) 2018 Tweag I/O
license: BSD3
github: tweag/asterius

extra-source-files:
  - CHANGELOG.md
  - LICENSE
  - README.md

ghc-options: -Wall

dependencies:
  - base
  - binaryen
  - bytestring
  - cereal
  - deepseq
  - ghc-prim
  - hashable
  - mtl
  - primitive
  - unliftio
  - unordered-containers
  - vector

library:
  source-dirs: src
  other-extensions:
    - ConstraintKinds
    - DefaultSignatures
    - DeriveDataTypeable
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - GADTs
    - LambdaCase
    - MagicHash
    - PolyKinds
    - OverloadedLists
    - StrictData
    - TypeFamilies
    - UnboxedTuples
    - UndecidableInstances

tests:
  nir-test:
    source-dirs: test
    main: nir-test.hs
    dependencies:
      - wasm-toolkit
    other-extensions:
      - OverloadedLists
      - OverloadedStrings
